vi /etc/prometheus/prometheus.yml
scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
    scrape_native_histograms: true

  # Scrape Node Exporter
  - job_name: "node"
    scrape_interval: 15s   # Prometheus scrapes every 15 seconds
    scrape_timeout: 10s    # Each scrape must finish within 10 seconds
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          app: "prometheus_node" 

Restart Prometheus service 
systemctl restart Prometheus


Promql 
rate(node_cpu_seconds_total{mode!="idle"}[5m])
node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes
node_filesystem_size_bytes - node_filesystem_avail_bytes

100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))
100 * (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"} / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"}))

